-- =============================================================================
-- Flyway example migration: V1__example_create_example_items_table.sql
-- =============================================================================
-- PURPOSE (read this file completely before writing your first real migration):
--   This is a fully commented EXAMPLE showing the conventions every migration
--   in this project must follow. It creates a small sample table so you can
--   watch Flyway work end-to-end on the first application startup.
--   The companion migration V2 shows a DATA (DML) migration.
--
-- FLYWAY FILE NAMING CONVENTION (MANDATORY):
--   V<version>__<description_in_snake_case>.sql
--     - "V"         -> prefix for a versioned migration (runs exactly once,
--                      in ascending version order).
--     - <version>    -> integer sequence: V1, V2, V3 ... (V10 runs after V9).
--     - "__"         -> DOUBLE underscore separating version and description.
--     - <description -> short snake_case summary, e.g. create_loan_simulations.
--     - .sql         -> PostgreSQL dialect (this project uses PostgreSQL).
--
-- HOW FLYWAY EXECUTES THIS FILE:
--   On every application startup Spring Boot triggers Flyway BEFORE JPA/Hibernate
--   initializes. Flyway reads the "flyway_schema_history" table in the target
--   database, compares it with the files in src/main/resources/db/migration and
--   runs every PENDING migration in order, each one inside a transaction,
--   recording version, description, checksum and execution time in the history
--   table. Once applied, a migration is IMMUTABLE: modifying the file later
--   changes its checksum and Flyway will refuse to start (validation error).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- STANDARD AUDIT COLUMNS (REQUIRED IN EVERY TABLE OF THIS PROJECT)
-- -----------------------------------------------------------------------------
-- Every JPA entity extends BaseEntity (from the internal base-project-spring-boot-starter),
-- which maps these columns. Keep the exact same names and types in every table:
--   id          UUID        -> primary key, generated by Hibernate (GenerationType.UUID).
--   created_at  TIMESTAMP   -> filled automatically by Spring Data auditing (@CreatedDate).
--   updated_at  TIMESTAMP   -> filled automatically by Spring Data auditing (@LastModifiedDate).
--   is_deleted  BOOLEAN     -> soft-delete flag. BaseEntity adds the Hibernate filter
--                              "is_deleted = false", so soft-deleted rows are
--                              invisible to the application.
-- Business columns come AFTER the id column, audit columns go at the end.
-- -----------------------------------------------------------------------------

-- Table names follow the project convention: plural, lowercase, snake_case.
CREATE TABLE example_items
(
    id          UUID         NOT NULL,                       -- PK from BaseEntity
    name        VARCHAR(100) NOT NULL,                       -- example business column
    description VARCHAR(255) NULL,                           -- example nullable column
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,          -- example column with default
    created_at  TIMESTAMP    NOT NULL,                       -- audit: BaseEntity
    updated_at  TIMESTAMP    NULL,                           -- audit: BaseEntity
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,         -- audit: soft-delete flag

    -- Constraint naming convention: pk_<table>, ck_<table>_<rule>
    CONSTRAINT pk_example_items PRIMARY KEY (id),
    CONSTRAINT ck_example_items_name_not_blank CHECK (LENGTH(TRIM(name)) > 0)
);

-- -----------------------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------------------
-- Index naming convention: ix_<table>_<columns>. Index the soft-delete flag and
-- any column you expect to filter or join on frequently.
CREATE INDEX ix_example_items_is_deleted ON example_items (is_deleted);
CREATE INDEX ix_example_items_name ON example_items (name);

-- -----------------------------------------------------------------------------
-- DATABASE DOCUMENTATION (optional but recommended)
-- -----------------------------------------------------------------------------
-- COMMENT ON statements are stored in PostgreSQL itself and are visible to any
-- developer inspecting the schema, even without access to this repository.
COMMENT ON TABLE example_items
    IS 'Example table created by the V1 Flyway migration to document project conventions. Remove it with a later migration (e.g. DROP TABLE example_items) once real modules exist.';
COMMENT ON COLUMN example_items.is_deleted
    IS 'Soft-delete flag managed by BaseEntity: rows with TRUE are filtered out by Hibernate.';
